### ISSUE TITLE
[Feature Request] Setting Option: Savage Pathfinder/Fantasy Companion

### ISSUE THREAD

**Issue by brunocalado** [ddbrown30/sfc#10]
Hi.

Can you create an option for Savage Pathfinder/Fantasy Companion? This would change the coin [description ](https://github.com/ddbrown30/sfc/issues/6) and some [other behavior](https://github.com/ddbrown30/sfc/issues/7).

**Comment by brunocalado** [comment]
Savage Pathfinder
![image](https://user-images.githubusercontent.com/4999783/232847085-dd1fa556-e5fe-4290-9cb9-d8be01de37a7.png)

**Comment by ddbrown30** [comment]
I'm probably not going to do this. I'd rather build out the tools to properly support both. That said, both PF and FC should be very close by default. I think the only difference between them at the moment is that the currency display will be on by default in FC and PF would want it off. Now that I've added that option, there's not much need for a separate mode for each.

**Comment by brunocalado** [comment]
> I'm probably not going to do this. I'd rather build out the tools to properly support both. That said, both PF and FC should be very close by default. I think the only difference between them at the moment is that the currency display will be on by default in FC and PF would want it off. Now that I've added that option, there's not much need for a separate mode for each.

The description field don't change?

**Comment by ddbrown30** [comment]
I have the same description field for both (which is based off the one you sent me).
