### ISSUE TITLE
Error due to the shortName flag being undefined

### ISSUE THREAD

**Issue by kristianserrano** [ddbrown30/sfc#11]
It seems the flag might not be getting set properly.

![Screenshot 2023-04-18 at 9 47 30 PM](https://user-images.githubusercontent.com/1796189/232945506-49b3f971-4683-4d56-bee1-90a6560859a6.png)

**Comment by ddbrown30** [comment]
It's a version bug. If you don't want to wait for me to fix it, you can fix it by going into the coin config and resetting to default.

**Comment by ddbrown30** [comment]
Fixed
