### ISSUE TITLE
[Bug] The description don't show on coins

### ISSUE THREAD

**Issue by brunocalado** [ddbrown30/sfc#12]
Hi

I clicked the button in the actor sheet to init the module, but I couldn't see the text [description](https://github.com/ddbrown30/sfc/issues/6).
![image](https://user-images.githubusercontent.com/4999783/233101450-cc4ead5f-d59e-452d-a092-5857b5aeae65.png)

**Comment by brunocalado** [comment]
The init button in settings also did not work.

**Comment by ddbrown30** [comment]
I'm able to repro this only on new actors the first time the init is run. If I run init a second time, it's correct. I'll have a bug fix for that shortly but please let me know if there's a different case I'm missing.

**Comment by ddbrown30** [comment]
Done
