### ISSUE TITLE
Change fields to number only

### ISSUE THREAD

**Issue by brunocalado** [ddbrown30/sfc#13]
Hi. 

Can you change the text box field to number only? 
thanks
![image](https://user-images.githubusercontent.com/4999783/233101953-ed25973a-2e7c-4f0e-8cb4-2d12da4b159d.png)

**Comment by brunocalado** [comment]
<input type="number" id="quantity" name="quantity" min="0" step="1">

**Comment by ddbrown30** [comment]
Switched it to a number. The min and step values are not working here for some reason. I would guess it has something to do with the way I'm injecting my html into the character sheet.

I also made some similar fixes to the coin config at the same time.
