### ISSUE TITLE
Improve Button CSS

### ISSUE THREAD

**Issue by brunocalado** [ddbrown30/sfc#14]
Hi.

Is it possible to improve the visual look of the button?

![image](https://user-images.githubusercontent.com/4999783/233104441-50991859-463e-49be-af98-bfdc1a31f987.png)

tks

**Comment by ddbrown30** [comment]
I absolutely suck at CSS. If you want to send me some CSS or make a pull request, I'd be happy to take it.

**Comment by brunocalado** [comment]
> I absolutely suck at CSS. If you want to send me some CSS or make a pull request, I'd be happy to take it.

chatGPT can help.
```
.btn-fantasia-medieval {
  background: linear-gradient(to bottom right, #b08d57, #9c6f43);
  font-family: Old English Text MT, Blackletter, serif;
  font-size: 20px;
  color: #fff;
  text-transform: uppercase;
  border: 2px solid #cda45e;
  border-radius: 8px;
  padding: 10px 20px;
  box-shadow: 2px 2px 2px #888;
  transition: background 0.3s ease-in-out, border-color 0.3s ease-in-out;
}

.btn-fantasia-medieval:hover {
  background: linear-gradient(to bottom right, #a98d4b, #8f7335);
  border-color: #a98d4b;
}

```

**Comment by ddbrown30** [comment]
I'll give that try but my comment was less about what to use to make it look good and more about the fact that I suck at getting the classes and everything right so that it actually applies it.

Also, I need to be careful about stomping over the default stuff. I'm doing my best to make sure that it all fits with whatever sheet someone is using so, for instance, I don't want to set the font.

I'll give that css a try at some point today and get back to you. Thanks for sending it.

**Comment by brunocalado** [comment]
> I'll give that try but my comment was less about what to use to make it look good and more about the fact that I suck at getting the classes and everything right so that it actually applies it.
> 
> Also, I need to be careful about stomping over the default stuff. I'm doing my best to make sure that it all fits with whatever sheet someone is using so, for instance, I don't want to set the font.
> 
> I'll give that css a try at some point today and get back to you. Thanks for sending it.

Maybe a very simple button then.

**Comment by kristianserrano** [comment]
I can submit a PR for it tomorrow.

**Comment by kristianserrano** [comment]
Rather than prescribing specific styles, I'll try to leverage styles already being used for the character sheet.

**Comment by ddbrown30** [comment]
> Rather than prescribing specific styles, I'll try to leverage styles already being used for the character sheet.

Yeah, that's what I usually rely on. The problem I found with the character sheet is that the button style it's using is basically invisible. It only appears on hover.

Hopefully you get get something that looks nice. I appreciate the help. :)

**Comment by kristianserrano** [comment]
Submitted a PR for this in #16.
