### ISSUE TITLE
error on loading SFC.

### ISSUE THREAD

**Issue by grendel111111** [ddbrown30/sfc#19]
I get this error on loading the world. It only occurs with the SFC module. install is 0.5.1 Swade 2.3.4  Foundry v10.291.

![image](https://user-images.githubusercontent.com/80164119/234043772-51f95d1b-bafb-4cfd-af69-f9f6e313de9b.png)

**Comment by brunocalado** [comment]
> I get this error on loading the world. It only occurs with the SFC module. install is 0.5.1 Swade 2.3.4 Foundry v10.291.
> 
> ![image](https://user-images.githubusercontent.com/80164119/234043772-51f95d1b-bafb-4cfd-af69-f9f6e313de9b.png)

I just tested. No error on a local instalation

**Comment by brunocalado** [comment]
I got an error when updating the icons
![image](https://user-images.githubusercontent.com/4999783/234048026-be823969-3cfd-447b-9721-6e9fa556ee71.png)

**Comment by ddbrown30** [comment]
Hmm, I'm not sure how you got into that state. Probably an issue with upgrading an old version. I've added a repair step on load that should hopefully fix up this bad data.
