### ISSUE TITLE
Not a number

### ISSUE THREAD

**Issue by brunocalado** [ddbrown30/sfc#2]
Hi. Great module.

I'm trying to make it work. What is wrong here?

![image](https://user-images.githubusercontent.com/4999783/232597008-8d412610-fa20-4647-bee8-464941d90e87.png)

**Comment by ddbrown30** [comment]
I'm not sure. Do you know what you did to get it into that state? What happens if you change one of the coin values? What is your currency setting the SWADE system settings?

**Comment by brunocalado** [comment]
> I'm not sure. Do you know what you did to get it into that state? What happens if you change one of the coin values? What is your currency setting the SWADE system settings?

Nothing. Do I need to do the iniatilize procedure before? I fear because it's my game world. The PCs have their coins in there.

**Comment by brunocalado** [comment]
> I'm not sure. Do you know what you did to get it into that state? What happens if you change one of the coin values? What is your currency setting the SWADE system settings?

Is it possible to avoid this actor update? Can it work by just dragging coins to the actor? Run a script in a big game world is scary.

**Comment by ddbrown30** [comment]
Nothing should have created a NaN state but yes, you should run the init before you start using it. That said, don't do it now or things might get more broken. 

If you disable the module, is it still broken?

A few questions. Please answer all of them. It'll help me understand what might be going wrong. 

- What is the currency setting in the SWADE settings i.e. wealth die, currency, or none?
- Did you ever run the init step or did you just enable the module, open a sheet and it was already NaN?
- Do all actors have a NaN or just one?
- If you can tell me everything you did before seeing that NaN, it will help a lot.

**Comment by ddbrown30** [comment]
Also, yes, the init step is optional but it will require you to manually calculate and set the coin counts. Just write down the currency amount before you start because as soon as you start entering coin values it will start updating the currency amount.

This might even fix your NaN issue (if you already know how much currency they had before) but I would suggest you wait until I fix the bug that caused the NaN as I can't guarantee it won't cause you other problems since I don't know why it happened in the first place.

**Comment by brunocalado** [comment]
What is the currency setting in the SWADE settings i.e. wealth die, currency, or none?
**none**

Did you ever run the init step or did you just enable the module, open a sheet and it was already NaN?
I never run the step.

Do all actors have a NaN or just one?
Just one. Linked
[fvtt-Actor-bruk-utuh.json.txt](https://github.com/ddbrown30/sfc/files/11256240/fvtt-Actor-bruk-utuh.json.txt)

Have you tried disabling your other modules?
Yes.
![image](https://user-images.githubusercontent.com/4999783/232622499-97eef1e0-d336-49ee-8df8-3c518e161117.png)

If you can tell me everything you did before seeing that NaN, it will help a lot.
I enabled your module. lol

**Comment by brunocalado** [comment]
> Also, yes, the init step is optional but it will require you to manually calculate and set the coin counts. Just write down the currency amount before you start because as soon as you start entering coin values it will start updating the currency amount.
> 
> This might even fix your NaN issue (if you already know how much currency they had before) but I would suggest you wait until I fix the bug that caused the NaN as I can't guarantee it won't cause you other problems since I don't know why it happened in the first place.

I tried to change the coin quantity, but the actor sheet didn't update.

https://user-images.githubusercontent.com/4999783/232622853-178f0a75-7ddd-4586-9a24-b5ccd21b99c0.mp4

**Comment by brunocalado** [comment]
I made a backup and did the step. No success.

**Comment by brunocalado** [comment]
> I made a backup and did the step. No success.

It added more coins. I already have coins on each sheet. But, even if I change this new coin, it don't update.
![image](https://user-images.githubusercontent.com/4999783/232623532-e729d4c3-fece-48ad-9c88-fa3141c50e1c.png)

**Comment by ddbrown30** [comment]
> Do all actors have a NaN or just one?
> Just one. Linked
> [fvtt-Actor-bruk-utuh.json.txt](https://github.com/ddbrown30/sfc/files/11256240/fvtt-Actor-bruk-utuh.json.txt)

Ah, I can see the problem. That actor's currency is set to an empty string. I'm probably not handling that case. I'll just add something to treat that as 0.

**Comment by ddbrown30** [comment]
Fixed. We now handle the case where currency is null or an empty string.
