### ISSUE TITLE
Existing Coins are not initialized

### ISSUE THREAD

**Issue by brunocalado** [ddbrown30/sfc#20]
Hi.

I have actors with pre existing coins (before your module). I Initialized the module and it works well. If I change the quantity of the newly created coins the module update. 

But, is there a way to the module to initialize taking in account existing coins which match the name?

![image](https://user-images.githubusercontent.com/4999783/234045831-4166076c-cd18-4172-b69e-4ca5b560d2bd.png)

tks

**Comment by ddbrown30** [comment]
I've intentionally not implemented this functionality. There is additional data associated with the items and there are cases where they can be deleted. Then there are issues around things like if the character has multiple items that match. I did not want to add a process that might end up causing data loss for a user.

My thoughts on the matter were that it's pretty quick to manually update the values on the 4 coins and then delete the old ones and so it wasn't worth the risk and potential undesired behaviour of automating it.
