### ISSUE TITLE
Coin Config for Selecting Custom Currency to Use 

### ISSUE THREAD

**Issue by DeathStapler** [ddbrown30/sfc#34]
Hello,

I use Savage Pathfinder and they have built-in currency items that are used for Platinum, Gold, etc.  Could the Coin Config be adjusted to allow for custom currency items, like Item Piles does for their currency configuration?

**Comment by ddbrown30** [comment]
It's not possible to do with the way SFC works. The items that the module uses have a bunch of extra data associated with them. It's not possible to safely and reliably put that data on items that exist outside of the module, particularly those in a compendium. The items are not really meant to be used like items either e.g. if you drag coins from one sheet to another, it doesn't combine them, it just makes a new stack (and those stacks will start fighting with each other if you mess around with them).

That said, what exactly are you trying to achieve here? The items in the PF module don't have any special logic associated with them. If you just want them to look the same as the ones in PF, you can just customize the SFC coins to point to the same art.

**Comment by DeathStapler** [comment]
I use the Coin Manager macro from SWPF - Enhanced module to distribute gold.  After testing, I notice that it just looks for an item called Gold, Silver, etc and adjusts the quantity.  The macro will work by renaming your "Gold coins" to "Gold".  

My players have multiple items for Gold.  Anything that is not on their character is called Gold (Bank), Gold (Home), or something like that.  I'll just use the standard currency for that. 

All that being said, I think I can make it work.   It would be nice if I could adjust the weight of the coins in the config to make them more in line with the weight of the metal.

I like this module, thanks for making it.
