### ISSUE TITLE
Coin names not sticking after logging out and back in

### ISSUE THREAD

**Issue by kristianserrano** [ddbrown30/sfc#9]
After changing the names of coins and reinitializing characters, initially the names update correctly. Logging out of the world and back in again, the updated names are lost.

![Screenshot 2023-04-18 at 12 28 10 PM](https://user-images.githubusercontent.com/1796189/232843418-7faa86bd-df34-4124-ad58-f687a2059302.png)

**Comment by kristianserrano** [comment]
This happens after a browser refresh as well.

**Comment by ddbrown30** [comment]
Fixed
